name: Release All Tar.gz

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { goos: linux,   goarch: amd64, arch_name: amd64 }
          - { goos: linux,   goarch: arm64, arch_name: aarch64 }
          - { goos: linux,   goarch: riscv64, arch_name: riscv64 }
          - { goos: darwin,  goarch: amd64, arch_name: amd64 }
          - { goos: darwin,  goarch: arm64, arch_name: aarch64 }
          - { goos: windows, goarch: amd64, arch_name: amd64 }
          - { goos: windows, goarch: arm64, arch_name: aarch64 }
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Build and package
        run: |
          NAME=nvdParser
          OUTNAME="${NAME}-${{ matrix.goos }}-${{ matrix.arch_name }}"
          BIN="$NAME"
          if [[ "${{ matrix.goos }}" == "windows" ]]; then
            BIN="$NAME.exe"
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o $BIN .
          tar -czf "${OUTNAME}.tar.gz" $BIN
          rm $BIN

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.goos }}-${{ matrix.arch_name }}
          path: "*.tar.gz"
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v5

      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          artifacts: ./**/*.tar.gz
          body: "Release for NVD Parser"
          # generateReleaseNotes: true

      - name: generate release notes
        run: |
          echo "NVD 2.0 JSON feed parser release" > release-notes.md
          echo -e "\n---\n\n<details><summary>SHA256SUMs</summary><br>\n\n\`\`\`" >> release-notes.md
          sha256sum **/* >> release-notes.md
          echo -e "\`\`\`\n</details>" >> release-notes.md
          echo -e "\n<details><summary>SHA512SUMs</summary><br>\n\n\`\`\`" >> release-notes.md
          sha512sum **/* >> release-notes.md
          echo -e "\`\`\`\n</details>" >> release-notes.md

      - name: update release body
        uses: ncipollo/release-action@v1
        with:
          bodyFile: release-notes.md
          allowUpdates: true
