name: Publish Release Assets

on:
  workflow_run:
    workflows: ["Release All Tar.gz"]   # must exactly match your build workflow's name
    types: [completed]

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Get the template from your repo (default branch)
      - name: Checkout repo (for release template)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Download and extract all artifacts from the triggering run
      - name: Download artifacts from build run
        uses: dawidd6/action-download-artifact@v6
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts

      - name: List downloaded files (debug)
        run: |
          echo "Artifacts tree:"
          ls -R artifacts || true
          echo
          echo "All tarballs found:"
          find artifacts -type f -name "*.tar.gz" -print | sort || true

      - name: Ensure tarballs exist
        run: |
          set -e
          count=$(find artifacts -type f -name "*.tar.gz" | wc -l | tr -d ' ')
          if [ "$count" -eq 0 ]; then
            echo "No .tar.gz files found in artifacts/ — did the build upload them?" >&2
            exit 1
          fi

      - name: Compute checksums (SHA-256 & SHA-512)
        run: |
          set -euo pipefail
          # Normalize path display: strip leading "artifacts/" from printed filenames
          find artifacts -type f -name "*.tar.gz" -print0 | sort -z \
            | xargs -0 -I{} sha256sum "{}" \
            | sed 's#  artifacts/#  #g' > sha256sums.txt

          find artifacts -type f -name "*.tar.gz" -print0 | sort -z \
            | xargs -0 -I{} sha512sum "{}" \
            | sed 's#  artifacts/#  #g' > sha512sums.txt

          echo "SHA-256:"
          cat sha256sums.txt
          echo
          echo "SHA-512:"
          cat sha512sums.txt

      - name: Build RELEASE.md from template + checksums
        run: |
          set -euo pipefail
          TAG="${{ github.event.workflow_run.head_branch }}"   # for tag-triggered runs, this is the tag (e.g., v0.1.1)
          DATE=$(date -u +'%Y-%m-%d')
          VERSION="${TAG#v}"

          # Fill simple placeholders in the template
          sed -e "s/{{TAG}}/${TAG}/g" \
              -e "s/{{DATE}}/${DATE}/g" \
              -e "s/{{VERSION}}/${VERSION}/g" \
              -e "s/{{RUN_ID}}/${{ github.event.workflow_run.id }}/g" \
              ".github/release_template.md" > RELEASE.md

          # Append collapsible checksum sections
          {
            echo
            echo "<details><summary><strong>SHA-256 checksums</strong></summary>"
            echo
            echo '```text'
            cat sha256sums.txt
            echo '```'
            echo
            echo "</details>"
            echo
            echo "<details><summary><strong>SHA-512 checksums</strong></summary>"
            echo
            echo '```text'
            cat sha512sums.txt
            echo '```'
            echo
            echo "</details>"
          } >> RELEASE.md

          echo "----- RELEASE.md -----"
          cat RELEASE.md

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.workflow_run.head_branch }}
          files: |
            artifacts/**/*.tar.gz
          body_path: RELEASE.md
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
